# Generated by Django 4.0.4 on 2022-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('beskrivelse', models.TextField()),
                ('tilbehør', models.TextField(max_length=100)),
            ],
        ),
    ]
