# Generated by Django 4.0.4 on 2022-05-16 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('beskrivelse', models.TextField()),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('tilbehør', models.TextField(max_length=100)),
                ('link1', models.URLField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('pris', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SlagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pris', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('navn', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('by', models.CharField(blank=True, max_length=50)),
                ('items', models.ManyToManyField(blank=True, related_name='slags', to='fritid.hobby')),
            ],
        ),
        migrations.AddField(
            model_name='hobby',
            name='kategori',
            field=models.ManyToManyField(related_name='item', to='fritid.kategori'),
        ),
    ]
