# Generated by Django 4.0.4 on 2022-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommentar',
            name='titel',
            field=models.TextField(default='2022-16-05'),
            preserve_default=False,
        ),
    ]
