# Generated by Django 4.0.4 on 2022-05-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0002_kommentar_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slagsmodel',
            name='gade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slagsmodel',
            name='land',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
