# Generated by Django 4.0.4 on 2022-05-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0003_slagsmodel_gade_slagsmodel_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommentar',
            name='navn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
