# Generated by Django 4.0.4 on 2022-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0005_alter_slagsmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='slagsmodel',
            name='oplysninger',
            field=models.TextField(default='2022-20-05'),
            preserve_default=False,
        ),
    ]
