# Generated by Django 4.0.4 on 2022-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritid', '0008_rename_titel_modeller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeller',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
